purging the resources

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,28 +1,34 @@
-name: Validate Deployment - KM Generic
+name: Validate Deployment
+
 on:
   push:
-    branches:
-
-      - main
-      - dev
-      - demo
+    branches: [main, dev, demo]
+  pull_request:
+    branches: [main, dev, demo]
+    types:
+      - opened
+      - ready_for_review
+      - reopened
+      - synchronize
+  merge_group:
   workflow_dispatch:
 
-  schedule:
-    - cron: '0 0,12 * * *'  # Runs at 12:00 AM and 12:00 PM GMT
-
-    
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    if: github.event_name != 'pull_request'
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
-      
-      - name: Debug Event Name
-        run: echo "Event Name - ${{ github.event_name }}"
-  
+
+      - name: Setup Azure CLI
+        run: |
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          az --version  # Verify installation
+
+      - name: Login to Azure
+        run: |
+          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
+
       - name: Run Quota Check
         id: quota-check
         run: |
@@ -30,18 +36,19 @@ jobs:
           export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
           export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
           export AZURE_SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-          export GPT_MIN_CAPACITY="490"
-          export TEXT_EMBEDDING_MIN_CAPACITY="80"
+          export GPT_MIN_CAPACITY="30"
+          export TEXT_EMBEDDING_MIN_CAPACITY="30"
           export AZURE_REGIONS="${{ vars.AZURE_REGIONS }}"
 
-          chmod +x infra/scripts/checkquota_km.sh
-          if ! infra/scripts/checkquota_km.sh; then
+          chmod +x scripts/checkquota.sh
+          if ! scripts/checkquota.sh; then
             # If quota check fails due to insufficient quota, set the flag
-            if grep -q "No region with sufficient quota found" infra/scripts/checkquota_km.sh; then
+            if grep -q "No region with sufficient quota found" scripts/checkquota.sh; then
               echo "QUOTA_FAILED=true" >> $GITHUB_ENV
             fi
             exit 1  # Fail the pipeline if any other failure occurs
           fi
+
 
       - name: Send Notification on Quota Failure
         if: env.QUOTA_FAILED == 'true'
@@ -62,52 +69,47 @@ jobs:
         if: env.QUOTA_FAILED == 'true'
         run: exit 1
 
+      - name: Install Bicep CLI
+        run: az bicep install
+      
       - name: Set Deployment Region
         run: |
           echo "Selected Region: $VALID_REGION"
-          echo "AZURE_LOCATION=$VALID_REGION" >> $GITHUB_ENV 
+          echo "AZURE_LOCATION=$VALID_REGION" >> $GITHUB_ENV
 
-      - name: Setup Azure CLI
-        run: |
-          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-          az --version  # Verify installation
-
-      - name: Login to Azure
-        run: |
-          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-      
-      - name: Install Bicep CLI
-        run: az bicep install
-    
       - name: Generate Resource Group Name
         id: generate_rg_name
         run: |
           echo "Generating a unique resource group name..."
-          TIMESTAMP=$(date +%Y%m%d%H%M%S)
-          COMMON_PART="ci-KMGeneric"
-          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          ACCL_NAME="docgen"  # Account name as specified
+          SHORT_UUID=$(uuidgen | cut -d'-' -f1)
+          UNIQUE_RG_NAME="arg-${ACCL_NAME}-${SHORT_UUID}"
           echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
-          echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}"
-
-      - name: Create Resource Group
+          echo "Generated RESOURCE_GROUP_NAME: ${UNIQUE_RG_NAME}"
+      
+      - name: Check and Create Resource Group
+        id: check_create_rg
         run: |
-          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.AZURE_LOCATION }}
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "false" ]; then
+            echo "Resource group does not exist. Creating..."
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.AZURE_LOCATION }} || { echo "Error creating resource group"; exit 1; }
+          else
+            echo "Resource group already exists."
+          fi
 
       - name: Generate Unique Solution Prefix
         id: generate_solution_prefix
         run: |
           set -e
-          COMMON_PART="km"
+          COMMON_PART="pslr"
           TIMESTAMP=$(date +%s)  
-          UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 5) 
+          UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
           UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
           echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
           echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
-
-
-      - name: Determine Tag Name Based on Branch
-        id: determine_tag
-        run: echo "tagname=${{ github.ref_name == 'main' && 'latest' || github.ref_name == 'dev' && 'dev' || github.ref_name == 'demo' && 'demo' || github.ref_name == 'dependabotchanges' && 'dependabotchanges' || github.head_ref || 'default' }}" >> $GITHUB_OUTPUT
 
       - name: Deploy Bicep Template
         id: deploy
@@ -115,116 +117,126 @@ jobs:
           set -e
           az deployment group create \
             --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
-            --template-file infra/main.bicep \
-            --parameters environmentName=${{env.SOLUTION_PREFIX}} contentUnderstandingLocation="Sweden Central" secondaryLocation="${{ env.AZURE_LOCATION }}" imageTag=${{ steps.determine_tag.outputs.tagname }}
-     
-            
-      - name: Extract AI Services and Key Vault Names
-        if: always()
+            --template-file infra/main.json \
+            --parameters \
+                environmentName="${{ env.SOLUTION_PREFIX }}" \
+                secondaryLocation="eastus2" \
+                deploymentType="GlobalStandard" \
+                gptModelName="gpt-4o" \
+                azureOpenaiAPIVersion="2024-05-01-preview" \
+                gptDeploymentCapacity="10" \
+                embeddingModel="text-embedding-ada-002" \
+                embeddingDeploymentCapacity="30" \
+                imageTag="latest"
+      
+      - name: Delete Bicep Deployment
+        if: success()
         run: |
-              echo "Fetching AI Services and Key Vault names before deletion..."
-              
-              # # Get Key Vault name
-              # KEYVAULT_NAME=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --resource-type "Microsoft.KeyVault/vaults" --query "[].name" -o tsv)
-              # echo "Detected Key Vault: $KEYVAULT_NAME"
-              # echo "KEYVAULT_NAME=$KEYVAULT_NAME" >> $GITHUB_ENV
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "true" ]; then
+            echo "Resource group exists. Cleaning..."
+            az group delete \
+                --name ${{ env.RESOURCE_GROUP_NAME }} \
+                --yes \
+                --no-wait
+            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+          else
+            echo "Resource group does not exist."
+          fi
+
+      - name: Wait for Resource Deletion to Complete
+        run: |
+          # List of resources to check based on SOLUTION_PREFIX
+          resources_to_check=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
+
+          # Get the list of resources in YAML format
+          resource_list=$(az resource list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output yaml)
           
-              # Get AI Services names and convert them into a space-separated string
-              AI_SERVICES=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --resource-type "Microsoft.CognitiveServices/accounts" --query "[].name" -o tsv | tr '\n' ' ')
-              
-              echo "Detected AI Services: $AI_SERVICES"
-              echo "AI_SERVICES=$AI_SERVICES" >> $GITHUB_ENV
+          # Maximum number of retries and retry intervals
+          max_retries=3
+          retry_intervals=(30 60 120)
+          retries=0
           
+          while true; do
+            resource_found=false
+            # Iterate through the resources to check
+            for resource in "${resources_to_check[@]}"; do
+              echo "Checking resource: $resource"
+              if echo "$resource_list" | grep -q "name: $resource"; then
+                echo "Resource '$resource' exists in the subscription."
+                resource_found=true
+              else
+                echo "Resource '$resource' does not exist in the subscription."
+              fi
+            done
+
+            # If any resource exists, retry
+            if [ "$resource_found" = true ]; then
+              retries=$((retries + 1))
+              if [ "$retries" -ge "$max_retries" ]; then
+                echo "Maximum retry attempts reached. Exiting."
+                break
+              else
+                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
+                sleep ${retry_intervals[$retries-1]}
+              fi
+            else
+              echo "No resources found. Exiting."
+              break
+            fi
+          done
+
+      - name: Purging the Resources
+        if: success()
+        run: |
+          set -e
+          # Purging resources based on solution prefix
+          echo "Purging resources..."
+
+          # List of resources to purge
+          resources_to_purge=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
+          
+          for resource in "${resources_to_purge[@]}"; do
+            echo "Purging resource: $resource"
+            if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$resource --verbose; then
+              echo "Failed to purge resource: $resource"
+            else
+              echo "Purged the resource: $resource"
+            fi
+          done
+
+          echo "Resource purging completed successfully"
 
       - name: Send Notification on Failure
         if: failure()
         run: |
           RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-      
-          # Construct the email body
+
           EMAIL_BODY=$(cat <<EOF
           {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the CKMv2 Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+            "body": "<p>Dear Team,</p><p>We would like to inform you that the Research Assistant Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
           }
           EOF
           )
-      
-          # Send the notification
+
           curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
             -H "Content-Type: application/json" \
             -d "$EMAIL_BODY" || echo "Failed to send notification"
-
-
-      - name: Delete Bicep Deployment
-        if: always()
-        run: |
-              set -e  
-              echo "Checking if resource group exists..."
-              rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-              if [ "$rg_exists" = "true" ]; then
-                echo "Resource group exist. Cleaning..."
-                az group delete \
-                    --name ${{ env.RESOURCE_GROUP_NAME }} \
-                    --yes \
-                    --no-wait
-                echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
-              else
-                echo "Resource group does not exists."
-              fi
-
-      - name: Wait for Soft Deletion of Key Vault and AI Services
-        if: always()
-        run: |
-                echo "Waiting for resources to be soft deleted..."
-            
-                # Wait for Key Vault to be soft deleted
-                if [ -n "${{ env.KEYVAULT_NAME }}" ]; then
-                  while true; do
-                    DELETED_VAULT=$(az keyvault show-deleted --name ${{ env.KEYVAULT_NAME }} --query "id" -o tsv 2>/dev/null || echo "")
-                    if [ -n "$DELETED_VAULT" ]; then
-                      echo "Key Vault soft deleted!"
-                      break
-                    fi
-                    echo "Key Vault not yet soft deleted. Retrying in 15s..."
-                    sleep 15
-                  done
-                fi
-
-            
-                # Wait for AI Services to be soft deleted
-                for AI_SERVICE in ${{ env.AI_SERVICES }}; do
-                  while true; do
-                    DELETED_AI_SERVICE=$(az cognitiveservices account list-deleted --query "[?name=='$AI_SERVICE'].id" -o tsv 2>/dev/null || echo "")
-                    if [ -n "$DELETED_AI_SERVICE" ]; then
-                      echo "AI Service $AI_SERVICE is soft deleted!"
-                      break
-                    fi
-                    echo "AI Service $AI_SERVICE not yet soft deleted. Retrying in 15s..."
-                    sleep 15
-                  done
-                done
-            
-      
-      - name: Purge Key Vault and AI Services
-        if: always()
-        run: |
-                  echo "Purging soft deleted resources..."
-                  
-                  # Ensure AI_SERVICES is properly split into individual services
-                  IFS=' ' read -r -a SERVICES <<< "${{ env.AI_SERVICES }}"
-        
-                  for AI_SERVICE in "${SERVICES[@]}"; do
-                    echo "Checking location for AI Service: $AI_SERVICE"
-        
-                    # Fetch AI Service location
-                    SERVICE_LOCATION=$(az cognitiveservices account list-deleted --query "[?name=='$AI_SERVICE'].location" -o tsv 2>/dev/null || echo "")
-        
-                    if [ -n "$SERVICE_LOCATION" ]; then
-                      echo "Purging AI Service $AI_SERVICE in $SERVICE_LOCATION"
-                      az cognitiveservices account purge --location "$SERVICE_LOCATION" --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --name "$AI_SERVICE"
-                    else
-                      echo "Could not determine location for AI Service: $AI_SERVICE. Skipping purge."
-                    fi
-                  done
-        shell: bash
-        
